### ISSUE TITLE
Create a Joomla theme that implements the Italia Design Guidelines

### ISSUE THREAD

**Issue by ruphy** [italia/design-joomla-theme#1]
Create a theme for Joomla based on the [User Interface design guidelines](
https://design-italia.readthedocs.io/it/stable/doc/user-interface.html).

Do include [the design web toolkit](https://github.com/italia/design-web-toolkit) as a dependency, and make sure you write your code in a way which is generic enough so that, later on, it be replaced by another toolkit (e.g. bootstrap) without too much effort.

Some example websites with the correct style
https://developers.italia.it
https://designers.italia.it

**GSoC mentor**: Somebody from in the #design team. If you are unsure who to ask you can check out https://slack.developers.italia.it

**Comment by tetekate2** [comment]
@ With regards to my skill level,  as a GSoC aspirant, I will like to take on this task.

**Comment by vinset** [comment]
I think it would be appropriate to create a template for Joomla 4, the next version that implements Bootstrap 4.

**Comment by tetekate2** [comment]
@vinset , Joomla 4 is still the alpha 1 release. IMO, I think it will be good to build for the latest stable release which is 3.8

**Comment by vinset** [comment]
You're right but the next version of Joomla will be the 3.9, migration version to Joomla 4. If we develop a template for Joomla 3.8 we would have an old version of Bootstrap (v.3) and a template unusable already from the next official version. Joomla 4 is the second alpha.

**Comment by tetekate2** [comment]
I can relate with your point @vinset , About using bootstrap 4, I thought all css and js will come for the  [the design web toolkit](https://github.com/italia/design-web-toolkit). Please correct me if I am wrong

**Comment by vinset** [comment]
You're right, the community is already working on the Bootstrap Italia, theme using Bootstrap 4. https://github.com/italia/bootstrap-italia

**Comment by francescozaia** [comment]
The new Bootstrap Italia theme is not yet ready for production, due to the lack of styling for some components that you can already find on the [design web toolkit](https://github.com/italia/design-web-toolkit), which is instead a mature project.

Said that, we're actively developing on Bootstrap Italia and in few weeks we count on having a lot more covered.

You can have a look at the [roadmap](https://github.com/italia/bootstrap-italia/projects/1) and the [documentation](https://italia.github.io/bootstrap-italia/docs/componenti/introduzione/) (sorry it’s all Italian there, but [Bootstrap 4 documentation](https://getbootstrap.com/docs/4.0/components/alerts/) remains valid for the majority of the components).

So, if you feel comfortable working with cutting edge stuff and you decide to follow the Joomla 4 road, feel free to pick the Bootstrap Italia theme, otherwise stick with the design web toolkit. 😉

If you prefer to have a chat about that, we can do that on the #design channel on Slack

**Comment by ruphy** [comment]
@francescozaia I think that for a GSoC project it is much better to go with cutting edge :) considering that we expect the first releases no sooner than in 3-5 months, the bootstrap 4 theme will have had time to mature a bit!

**Comment by tetekate2** [comment]
@ruphy we had a discuss on this on the #design channel on Slack. You are just confirming the conclusion we reached at :astonished:

**Comment by jeckodevelopment** [comment]
Good idea and nice project.
I'd be happy to help :)
In any case, i'd recommend to build it for Joomla 3.8 at this time.

**Comment by ruphy** [comment]
@jeckodevelopment we're having a call open looking for mentors, would you be interested to help officially? :) Please poke me on our [slack](https://slack.developers.italia.it) and I can guide you to understand the process

**Comment by vinset** [comment]
Joomla's team has published the new roadmap for Joomla 4.
The stable release is scheduled for the end of 2018.
https://developer.joomla.org/roadmap.html

**Comment by jeckodevelopment** [comment]
Given that GSOC should happen during summer this year, as said, i believe it's better to stick with 3.8

**Comment by tetekate2** [comment]
jeckodevelopment what about developing in 4.0 and then backport ? I am sure a 4.0 theme will work on 3.8 but the reverse may not hold true

**Comment by jeckodevelopment** [comment]
because 4.0 is still in Alpha phase and many things can change until the stable release (end of the year)

**Comment by vinset** [comment]
The main developers of extensions for Joomla are already modifying their extensions so that they are compatible with Joomla 4 abandoning the support to 3.8.
Developing the template for j3 is equivalent to developing something that will not be used by anyone in 10 months!

**Comment by jeckodevelopment** [comment]
A real pity that @teamdigitale decided to not support this project anymore.
@libremente

**Comment by libremente** [comment]
Moving to https://github.com/italia/design-joomla-theme/issues/2 to start a new thread.

**Comment by libremente** [comment]
@jeckodevelopment we are still on it, just opening a [new thread](https://github.com/italia/design-joomla-theme/issues/2) for a more "updated" conversation :wink:
